version: '3'

services:
  usermanagement:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=usermanagement #changeit
      - POSTGRES_USER=username #changeit
      - POSTGRES_PASSWORD=pass #changeit
      - AZURE_AD_TENANT_ID=your_tenant_id
      - AZURE_AD_CLIENT_ID=your_client_id
      - AZURE_AD_CLIENT_SECRET=your_client_secret
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: usermanagement
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    networks:
      - app-network

volumes:
  postgres-data: 

networks:
  app-network:
